import type { AnchorWallet } from "./wallet";

type ChatFile = { name: string; type: string; size: number; data: string };
type ChatMessage = { id: string; sender: string; text: string; sentAt: number; file?: ChatFile };
type ChatRoom = { roomKey: string; offerId: number | null; title: string; participants: string[] };
const MAX_FILE_BYTES = 10 * 1024 * 1024;

export function initChatDrawer(walletChange: (callback: (wallet: AnchorWallet | null) => void) => void) {
  const button = document.querySelector<HTMLButtonElement>("#chat-toggle")!, drawer = document.querySelector<HTMLElement>("#chat-drawer")!;
  const close = document.querySelector<HTMLButtonElement>("#chat-close")!, messages = document.querySelector<HTMLElement>("#chat-messages")!;
  const roomsElement = document.querySelector<HTMLElement>("#chat-rooms")!, roomTitle = document.querySelector<HTMLElement>("#chat-room-title")!;
  const form = document.querySelector<HTMLFormElement>("#chat-form")!, input = document.querySelector<HTMLTextAreaElement>("#chat-input")!;
  const fileInput = document.querySelector<HTMLInputElement>("#chat-file")!, fileLabel = document.querySelector<HTMLElement>("#chat-file-label")!;
  const status = document.querySelector<HTMLElement>("#chat-status")!, hint = document.querySelector<HTMLElement>("#chat-hint")!;
  if (!button || !drawer || !close || !messages || !roomsElement || !roomTitle || !form || !input || !fileInput || !fileLabel || !status || !hint) return;
  const initialRoom = location.pathname.match(/^\/contract\/([^/]+)/)?.[1] ? `contract:${location.pathname.match(/^\/contract\/([^/]+)/)![1]}` : "";
  const socketUrl = import.meta.env.PUBLIC_CHAT_URL || `${location.protocol === "https:" ? "wss" : "ws"}://${location.hostname}:8787`;
  let wallet: AnchorWallet | null = null, socket: WebSocket | null = null, sessionToken: string | null = null, activeRoom = initialRoom, selectedFile: File | null = null;
  let rooms: ChatRoom[] = [];
  const sessionKey = (address: string) => `linkdeal:chat-session:${address}`;
  const roomsKey = (address: string) => `linkdeal:chat-rooms:${address}`;
  const loadRooms = (address: string): ChatRoom[] => {
    try { return JSON.parse(localStorage.getItem(roomsKey(address)) ?? "[]") as ChatRoom[]; } catch { return []; }
  };
  const short = (address: string) => `${address.slice(0, 4)}…${address.slice(-4)}`;
  const roomLabel = (room: ChatRoom) => {
    const keyParticipants = room.roomKey.split(":").slice(2);
    const participant = [...room.participants, ...keyParticipants].find((address) => address !== wallet?.publicKey.toBase58());
    return `${short(participant ?? "brak adresu")} · ${room.title}`;
  };
  const send = (payload: object) => { if (socket?.readyState === WebSocket.OPEN) socket.send(JSON.stringify(payload)); };
  const setStatus = (text: string, kind: string) => { status.textContent = text; status.className = `badge badge-${kind}`; };
  function renderRooms() { roomsElement.replaceChildren(...rooms.map((room) => { const item = document.createElement("button"); item.type = "button"; item.className = `btn btn-ghost btn-sm h-auto min-h-0 w-full min-w-0 justify-start overflow-hidden text-left ${room.roomKey === activeRoom ? "btn-active" : ""}`; item.textContent = roomLabel(room); item.title = item.textContent; item.classList.add("truncate", "whitespace-nowrap"); item.onclick = (event) => { event.preventDefault(); if (room.roomKey !== activeRoom) connect(room.roomKey); }; return item; })); }
  function render(message: ChatMessage) { const own = wallet?.publicKey.toBase58() === message.sender; const row = document.createElement("div"); row.className = `flex ${own ? "justify-end" : "justify-start"}`; const bubble = document.createElement("div"); bubble.className = `max-w-[90%] rounded-box p-2 text-sm ${own ? "bg-primary text-primary-content" : "bg-base-200"}`; const meta = document.createElement("div"); meta.className = "mb-1 text-xs opacity-70"; meta.textContent = `${short(message.sender)} · ${new Date(message.sentAt).toLocaleTimeString()}`; bubble.append(meta); if (message.text) { const text = document.createElement("p"); text.className = "whitespace-pre-wrap break-words"; text.textContent = message.text; bubble.append(text); } if (message.file) { const link = document.createElement("a"); link.className = "mt-2 block break-all underline"; link.download = message.file.name; link.href = `data:${message.file.type || "application/octet-stream"};base64,${message.file.data}`; link.textContent = `📎 ${message.file.name} (${Math.ceil(message.file.size / 1024)} KB)`; bubble.append(link); } row.append(bubble); messages.append(row); messages.scrollTop = messages.scrollHeight; }
  function update() { const ready = Boolean(wallet && socket?.readyState === WebSocket.OPEN); input.disabled = !ready; fileInput.disabled = !ready; setStatus(socket?.readyState === WebSocket.OPEN ? (wallet ? "Połączono" : "Podpisz wallet") : "Offline", ready ? "success" : "warning"); }
  function connect(roomKey: string) { activeRoom = roomKey; messages.replaceChildren(); const currentRoom = rooms.find((room) => room.roomKey === roomKey); roomTitle.textContent = currentRoom ? roomLabel(currentRoom) : "Wybierz rozmowę"; renderRooms(); socket?.close(); socket = new WebSocket(socketUrl); socket.onopen = () => { setStatus("Autoryzacja…", "warning"); const payload: { type: string; roomKey: string; address?: string; token?: string } = { type: "hello", roomKey }; if (wallet) { payload.address = wallet.publicKey.toBase58(); payload.token = sessionToken ?? localStorage.getItem(sessionKey(payload.address)) ?? undefined; } socket?.send(JSON.stringify(payload)); }; socket.onclose = () => setStatus("Offline", "error"); socket.onerror = () => { hint.textContent = "Nie można połączyć się z serwerem chatu."; }; socket.onmessage = async (event) => { const p = JSON.parse(event.data) as { type: string; message?: string | ChatMessage; nonce?: string; token?: string; messages?: ChatMessage[]; rooms?: ChatRoom[] }; if (p.type === "challenge" && wallet && typeof p.message === "string") send({ type: "auth", nonce: p.nonce, address: wallet.publicKey.toBase58(), signature: await wallet.signMessage(p.message) }); else if (p.type === "ready") { if (p.token && wallet) { sessionToken = p.token; localStorage.setItem(sessionKey(wallet.publicKey.toBase58()), p.token); } (p.messages ?? []).forEach(render); update(); } else if (p.type === "rooms") { rooms = p.rooms ?? []; if (wallet) localStorage.setItem(roomsKey(wallet.publicKey.toBase58()), JSON.stringify(rooms)); renderRooms(); } else if (p.type === "message" && p.message && typeof p.message !== "string") render(p.message); else if (p.type === "error") hint.textContent = typeof p.message === "string" ? p.message : "Błąd chatu."; }; update(); }
  button.onclick = () => { drawer.classList.toggle("hidden"); if (!drawer.classList.contains("hidden") && wallet && !socket) { const room = activeRoom || rooms[0]?.roomKey; if (room) connect(room); else hint.textContent = "Otwórz umowę i kliknij chat, aby rozpocząć rozmowę."; } }; close.onclick = () => drawer.classList.add("hidden");
  fileInput.onchange = () => { selectedFile = fileInput.files?.[0] ?? null; fileLabel.textContent = selectedFile?.name ?? "📎"; };
  form.onsubmit = async (event) => { event.preventDefault(); if (!wallet || !socket || socket.readyState !== WebSocket.OPEN || (!input.value.trim() && !selectedFile)) return; if (selectedFile && selectedFile.size > MAX_FILE_BYTES) { hint.textContent = "Maksymalny rozmiar pliku to 10 MB."; return; } const payload: { type: string; text: string; file?: ChatFile } = { type: "message", text: input.value.trim() }; if (selectedFile) payload.file = { name: selectedFile.name, type: selectedFile.type, size: selectedFile.size, data: await new Promise<string>((resolve, reject) => { const reader = new FileReader(); reader.onload = () => resolve(String(reader.result).split(",")[1] ?? ""); reader.onerror = () => reject(new Error("Nie udało się odczytać pliku.")); reader.readAsDataURL(selectedFile!); }) }; send(payload); input.value = ""; fileInput.value = ""; selectedFile = null; fileLabel.textContent = "📎"; };
  walletChange((next) => { wallet = next; const address = next?.publicKey.toBase58(); sessionToken = address ? localStorage.getItem(sessionKey(address)) : null; rooms = address ? loadRooms(address) : []; renderRooms(); socket?.close(); socket = null; if (next && !drawer.classList.contains("hidden") && (activeRoom || rooms[0]?.roomKey)) connect(activeRoom || rooms[0].roomKey); update(); });
}
